// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBv5DUuItVn34XtQdqssVv51uEiC6SnEHY',
    appId: '1:326227744653:web:7e4eff1fa45f0ca6858fc4',
    messagingSenderId: '326227744653',
    projectId: 'khanadelivery-9710b',
    authDomain: 'khanadelivery-9710b.firebaseapp.com',
    storageBucket: 'khanadelivery-9710b.appspot.com',
    measurementId: 'G-H2VJT0LFZ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGB28kElTMdsSja4p_1-Tto533SEusk5Y',
    appId: '1:326227744653:android:52ead67c2db8fd42858fc4',
    messagingSenderId: '326227744653',
    projectId: 'khanadelivery-9710b',
    storageBucket: 'khanadelivery-9710b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4J_Q7k5A_VKFcjEcMyrOzlbRfelIqfvw',
    appId: '1:326227744653:ios:c54b814aa691f208858fc4',
    messagingSenderId: '326227744653',
    projectId: 'khanadelivery-9710b',
    storageBucket: 'khanadelivery-9710b.appspot.com',
    iosBundleId: 'com.khana.delivery.khanaDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4J_Q7k5A_VKFcjEcMyrOzlbRfelIqfvw',
    appId: '1:326227744653:ios:c54b814aa691f208858fc4',
    messagingSenderId: '326227744653',
    projectId: 'khanadelivery-9710b',
    storageBucket: 'khanadelivery-9710b.appspot.com',
    iosBundleId: 'com.khana.delivery.khanaDelivery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBv5DUuItVn34XtQdqssVv51uEiC6SnEHY',
    appId: '1:326227744653:web:5f493193b525c103858fc4',
    messagingSenderId: '326227744653',
    projectId: 'khanadelivery-9710b',
    authDomain: 'khanadelivery-9710b.firebaseapp.com',
    storageBucket: 'khanadelivery-9710b.appspot.com',
    measurementId: 'G-4NCLTWS59J',
  );
}
